airbnb_dbt:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', default='AIRBNB') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', default='DEV') }}"
      threads: "{{ env_var('DBT_NUM_THREADS', default=1) }}"
      type: "{{ env_var('DBT_TYPE', default='snowflake') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', default='COMPUTE_WH') }}"
  target: "{{ env_var('DBT_TARGET', default='dev') }}"
